# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Pranaydeep Singh
tagline:          'c1pher'
description:      'Doctoral Candidate at LT3, UGent'
url:              https://pranaydeeps.github.io/
baseurl:          https://pranaydeeps.github.io/

author:
  name:           'Pranaydeep Singh'
  url:            https://github.com/pranaydeeps

paginate:         5
paginate_path: "Blog/page:num/"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pranaydeeps

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
