# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            pranaydeep-af
tagline:          'A Jekyll theme'
description:      'NLP, Linguistics, Literature, Progressive Music and all kinds of stuff'
url:              'https://pranaydeep-af.github.io'
baseurl:          '/'

author:
  name:           'Pranaydeep'
  url:            https://github.com/pranaydeep-af

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pranaydeep-af

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
