# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            pranaydeeps
tagline:          'My Journal'
description:      'NLP, Linguistics, Literature, Progressive Music and all kinds of stuff'
url:              https://pranaydeeps.github.io/
baseurl:          'https://pranaydeeps.github.io/'

author:
  name:           'Pranaydeep'
  url:            https://github.com/pranaydeeps

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pranaydeeps

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
